import = [
	"~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

live_config_reload = true

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[font]
size = 14

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
dynamic_title = true
opacity = 1
dynamic_padding = true
decorations = "None"

[scrolling]
multiplier = 12

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{ key = "ArrowLeft", mods = "Alt", chars = "\u001bb" },
	{ key = "ArrowRight", mods = "Alt", chars = "\u001bf" }
]
