tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "coreutils"
brew "fzf"
brew "git"
brew "git-gui"
brew "git-open"
brew "python@3.11"
brew "htop"
brew "hugo"
brew "jq"
brew "lsd"
brew "mas"
brew "midnight-commander"
brew "neovim"
brew "nmap"
brew "nvm"
brew "rsync"
brew "starship"
brew "telnet"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "watchman"
brew "wget"
brew "zlib"
brew "zplug"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "alacritty"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "kap"
cask "maestral"
cask "mouse-fix"
cask "skype"
cask "spotify"
cask "tor-browser"
cask "vlc"
mas "1Blocker", id: 1365531024
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
