#!/bin/zsh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_shadow                on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0 #0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# create up to 9 Mission Control Spaces
SPACES_COUNT="$(yabai -m query --spaces | jq '. | length')"
MISSING_SPACES_COUNT=$((9-$SPACES_COUNT))

echo "Creating $MISSING_SPACES_COUNT spaces (if missing)"
repeat $MISSING_SPACES_COUNT {
  yabai -m space --create
}

# add labels to the Spaces
typeset -A SPACE_LABELS
SPACE_LABELS=(
  1 www
  2 dev
  3 code
  4 term
  5 msgs
  6 music
)

for key ("${(@k)SPACE_LABELS}") 
do 
  echo "Labeling space $key as $SPACE_LABELS[$key]"
  yabai -m space $key --label $SPACE_LABELS[$key]
done

# assign apps to the particular Spaces
yabai -m rule --add app="Code" space=3
yabai -m rule --add app="Alacritty" space=4
yabai -m rule --add app="Discord" space=5
yabai -m rule --add app="Slack" space=5
yabai -m rule --add app="^Spotify$" space=6
yabai -m rule --add app="^Endel$" space=6

# disable yabai for particular apps
UNMANAGED_APPS=("System Preferences" AnyConnect Kap Messages Simulator Mail Calendar Cron Todoist Spark Stickies)
for app ("$UNMANAGED_APPS[@]") yabai -m rule --add app=$app manage=off

## disable yabai for particular apps with additional parameters
yabai -m rule --add app="Bitwarden" manage=off grid=6:4:1:1:2:4

# perfectly center floating, nonresizable apps
events=('application_launched')
apps=('System Preferences' 'AnyConnect')

read -r -d '' action <<- 'EOF'
  window="$(yabai -m query --windows --window)"
  display="$(yabai -m query --displays --window)"
  coords="$(jq \
    --argjson window "${window}" \
    --argjson display "${display}" \
    -nr '(($display.frame | .x + .w / 2) - ($window.frame.w / 2) | tostring)
      + ":"
      + (($display.frame | .y + .h / 2) - ($window.frame.h / 2) | tostring)')"
  yabai -m window --move "abs:${coords}"
EOF

(( ${#apps[@]} ))   && app_query="app=\"^($(IFS=\|;echo "${apps[*]}"))\$\""
for event in "${events[@]}"; do
  yabai -m signal --add label="${0}_signal_${event}" event="${event}" \
    $(eval "${app_query}}") action="${action}"
done

yabai -m signal --add event=space_changed action="open -gj 'swiftbar://refreshPlugin?name=yabai.1d.js'"