#!/bin/zsh

# Scripting addition reload
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Global settings
yabai -m config layout                       bsp
yabai -m config window_placement             second_child
yabai -m config window_topmost on # Make floating windows always on top
yabai -m config window_shadow float # Add shadows only to floating window

# Gaps
yabai -m config top_padding     10
yabai -m config bottom_padding  10
yabai -m config left_padding    10
yabai -m config right_padding   10
yabai -m config window_gap      10
yabai -m config external_bar main:38:0 # Adds padding for sketchybar on external display only

# Mouse settings
yabai -m config mouse_modifier alt
# yabai -m config mouse_follows_focus on # Move cursor to window selected by keyboard
yabai -m config mouse_action1 move # LMB + ⌥ + drag to move window
yabai -m config mouse_action2 resize # RMB + ⌥ + drag to resize window
yabai -m config mouse_drop_action swap # Swap windows on dragging one onto another

# Disable yabai for particular apps
UNMANAGED_APPS=("System Settings" Kap Simulator Stickies Calculator Finder Home Loom "Raycast Settings" MacGPT Telegram Dropshare "Toggl Track" Session Alice "Zelda AI" "zelda-ai-client")
for app ("$UNMANAGED_APPS[@]") yabai -m rule --add app=$app manage=off

UNMANAGED_CENTERED_APPS=(Bitwarden Messages Calendar)
for app ("$UNMANAGED_CENTERED_APPS[@]") yabai -m rule --add app=$app manage=off grid=6:4:1:1:2:4


# assign apps to the particular Spaces
yabai -m rule --add app="Arc" space=1

SPACE_2_APPS=(Code Neovide)
for app ("$SPACE_2_APPS[@]") yabai -m rule --add app=$app space=2

SPACE_3_APPS=(Slack Discord)
for app ("$SPACE_3_APPS[@]") yabai -m rule --add app=$app space=3

SPACE_4_APPS=(Spotify)
for app ("$SPACE_4_APPS[@]") yabai -m rule --add app=$app space=4

# add labels to the Spaces
typeset -A SPACE_LABELS
SPACE_LABELS=(
  1 www
  2 dev
  3 chat
  4 music
)

for key ("${(@k)SPACE_LABELS}")
do
  echo "Labeling space $key as $SPACE_LABELS[$key]"
  yabai -m space $key --label $SPACE_LABELS[$key]
done

# Force app windows always on top
AOT_APPS=(Telegram)
for app ("$AOT_APPS[@]") yabai -m rule app=$app layer=above

# App-based fixes
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
